CREATE TYPE contact_number_varray AS VARRAY(2) OF VARCHAR2(15);

create type person as object (
    first_name VARCHAR2(50),
    last_name VARCHAR2(50) ,
    contact_number contact_number_varray,
    email VARCHAR2(100),
    gender CHAR(1),
    date_of_birth DATE
);

CREATE TABLE persons of person;


CREATE TABLE patients (
  patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  personal_info REF person
);


CREATE TABLE doctors (
  doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  specialization VARCHAR2(100),
  personal_info REF person,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE appointments (
  appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER NOT NULL,
  appointment_date TIMESTAMP NOT NULL,
  status VARCHAR2(10) CHECK (status IN ('Scheduled', 'Completed', 'Cancelled')) NOT NULL,
  remarks VARCHAR2(4000),
  CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
  CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
);



CREATE TABLE medical_records (
  record_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER NOT NULL,
  visit_date DATE NOT NULL,
  diagnosis CLOB CONSTRAINT chk_diagnosis_json CHECK (diagnosis IS JSON),
  treatment VARCHAR2(4000) NOT NULL,
  prescription VARCHAR2(4000),
  audio_notes BLOB,
  CONSTRAINT fk_medical_records_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
  CONSTRAINT fk_medical_records_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
);

CREATE TABLE lab_results (
  lab_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  test_name VARCHAR2(100) NOT NULL,
  test_date TIMESTAMP NOT NULL,
  result_text VARCHAR2(4000),
  result_image BLOB,
  CONSTRAINT fk_lab_results_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id)
);

CREATE type medication as object (
  name VARCHAR2(100),
  description CLOB ,
  side_effects VARCHAR2(4000)
);

create type medications as table of medication;

CREATE TABLE prescriptions (
  prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id NUMBER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  prescription_medications medications,
  CONSTRAINT fk_prescriptions_record FOREIGN KEY (record_id) REFERENCES medical_records(record_id)
)
nested table prescription_medications store as tab_medications;

CREATE TABLE billing (
  bill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id NUMBER NOT NULL,
  total_amount NUMBER(10, 2) NOT NULL,
  payment_status VARCHAR2(10) CHECK (payment_status IN ('Pending', 'Paid')) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_billing_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id)
);

CREATE TABLE rooms (
  room_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_number VARCHAR2(10) UNIQUE NOT NULL,
  room_type VARCHAR2(10) CHECK (room_type IN ('General', 'Private', 'ICU')) NOT NULL,
  status VARCHAR2(10) CHECK (status IN ('Available', 'Occupied')) NOT NULL
);

CREATE TABLE admissions (
  admission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  room_id NUMBER NOT NULL,
  admission_date TIMESTAMP NOT NULL,
  discharge_date TIMESTAMP,
  reason VARCHAR2(4000) NOT NULL,
  status VARCHAR2(10) CHECK (status IN ('Admitted', 'Discharged')) NOT NULL,
  video_recording BLOB,
  CONSTRAINT fk_admissions_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
  CONSTRAINT fk_admissions_room FOREIGN KEY (room_id) REFERENCES rooms(room_id)
);

CREATE TABLE patients_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    contact_number contact_number_varray
);

CREATE OR REPLACE TRIGGER log_patient_deletion
AFTER DELETE ON patients
FOR EACH ROW
BEGIN
    INSERT INTO patients_audit (patient_id, first_name, last_name, contact_number)
    VALUES (:OLD.patient_id, deref(:OLD.personal_info).first_name, deref(:OLD.personal_info).last_name, deref(:OLD.personal_info).contact_number);
END;



CREATE TABLE doctors_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id NUMBER,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    contact_number contact_number_varray
);

CREATE OR REPLACE TRIGGER log_doctor_deletion
AFTER DELETE ON doctors
FOR EACH ROW
BEGIN
    INSERT INTO doctors_audit (doctor_id, first_name, last_name, contact_number)
    VALUES (:OLD.doctor_id, deref(:OLD.personal_info).first_name, deref(:OLD.personal_info).last_name, deref(:OLD.personal_info).contact_number);
END;